version: "3.5"
services:
  postgresql:
    build: ./
    container_name: postgre-todo
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - "5432:5432"
    user: root
    volumes:
      - pq-todo:/var/lib/pgdata
volumes:
  pq-todo:
    driver: local
